version: '3.8'

services:
  user-auth:
    build:
      context: ./user-auth
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: >
      chmod +x migration.sh && sh -c ./migration.sh
    environment:
      PORT: 8001
      DATABASE.HOST: db
      DATABASE.PORT: 5432
      DATABASE.DBNAME: postgres
      DATABASE.USERNAME: username
      DATABASE.PASSWORD: password


  product-management:
    build:
      context: ./product
    ports:
      - "8002:8002"
    depends_on:
      - db
    command: >
      chmod +x migration.sh && sh -c ./migration.sh
    environment:
      PORT: 8002
      DATABASE.HOST: db
      DATABASE.PORT: 5432
      DATABASE.DBNAME: postgres
      DATABASE.USERNAME: username
      DATABASE.PASSWORD: password

  order-management:
    build:
      context: ./order-management
    ports:
      - "8003:8003"
    depends_on:
      - db
    command: >
      chmod +x migration.sh && sh -c ./migration.sh
    environment:
      PORT: 8003
      DATABASE.HOST: db
      DATABASE.PORT: 5432
      DATABASE.DBNAME: postgres
      DATABASE.USERNAME: username
      DATABASE.PASSWORD: password

  db:
    image: postgres:14-alpine
    # container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  dev-db-data:
# Add additional configuration as needed