// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package dbsqlc

import (
	"database/sql"
)

type SubOrder struct {
	ID            int32
	UniqueOrderID string
	ProductID     int32
	Quantity      int32
	Status        string
	Version       int32
	Created       sql.NullTime
	Updated       sql.NullTime
}

type UserOrder struct {
	ID            string
	UserID        int32
	UniqueOrderID string
	Status        string
	TotalPrice    float64
	Version       int32
	Created       sql.NullTime
	Updated       sql.NullTime
}
